language: go
sudo: false

before_install:
  - cd core

go:
  - 1.12.x

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1

script:
  - diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go' -not -path "./core/vendor/*")) 
  - make && make test
  - cd ./test && bash ci_pipeline.sh

cache:
  directories:
    - .cache
